[RecoilPresets]
Enabled = true
VerticalRecoil = 3.00
HorizontalRecoil = 0.00

[Controller]
Enabled = false
Multiplier = 10

[Keys]
# Use https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
# And then convert the key code to decimal
# Toggle Key (e.g. 20 = CAPS LOCK)
ToggleRecoilKey = 20
ToggleRecoilEnabled = false
PrimaryKey = 49
SecondaryKey = 50
TertiaryKey = 51

[Theme]
BackgroundColour = RGB(30, 30, 30)
TextColour = RGB(230, 230, 230)
LineColour = RGB(180, 180, 180)
